const fs=require("fs"),path=require("path"),r=path.join(__dirname,"..");
const w=(rel,c)=>{const p=path.join(r,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,c)};
w("apps/api/src/index.ts",[
'import "dotenv/config";',
'import { serve } from "@hono/node-server";',
'import { Hono } from "hono";',
'import { cors } from "hono/cors";',
'import { WebSocketServer } from "ws";',
'import { createServer } from "node:http";',
'import { ChatMessageSchema } from "@omnichat/chat-types";',
'import { ChatHub } from "./hub.js";',
'const port=Number(process.env.PORT??8787);',
'const hub=new ChatHub();',
'const app=new Hono();',
'app.use("*",cors({origin:"*"}));',
'app.get("/health",(c)=>c.json({ok:true}));',
'app.get("/api/public/channels/lookup",(c)=>{',
'  const slug=c.req.query("slug")??"";',
'  return c.json({enabled:false,roomId:null,displayName:slug,platformsActive:[],live:false});',
'});',
'app.post("/api/ingest/:platform",async(c)=>{',
'  const wsId=c.req.header("x-workspace-id")??"demo";',
'  const body=await c.req.json().catch(()=>null);',
'  const parsed=ChatMessageSchema.safeParse(body?.message??body);',
'  if(!parsed.success)return c.json({error:"invalid message"},400);',
'  hub.ingest("room:"+wsId,parsed.data);',
'  hub.ingest("room:"+wsId+":public",parsed.data);',
'  return c.json({ok:true});',
'});',
'const httpServer=createServer();',
'const wss=new WebSocketServer({noServer:true});',
'wss.on("connection",(ws,req)=>{',
'  const url=new URL(req.url??"/","http://localhost");',
'  const roomId=url.searchParams.get("room")??"room:demo:public";',
'  hub.subscribe(roomId,ws);',
'  ws.on("close",()=>hub.unsubscribe(roomId,ws));',
'});',
'httpServer.on("upgrade",(req,socket,head)=>{wss.handleUpgrade(req,socket,head,(ws)=>{wss.emit("connection",ws,req);});});',
'serve({fetch:app.fetch,port,createServer:()=>httpServer});',
'console.log("API http://localhost:"+port+"  WS ws://localhost:"+port+"?room=room:demo:public");',
].join("\n"));
w("README.md","# Om-nichat\n\n```bash\npnpm install\npnpm --filter @omnichat/chat-types build\npnpm --filter @omnichat/api dev\n```\n");
console.log("index ok");
